import type { SurahNumber } from "@/types/domain"

/**
 * The 114 surahs of the Quran, in mushaf order. Reusable reference data:
 * records store the stable `number` (the Quran order matters for exams),
 * never the display name.
 */
export interface Surah {
  number: SurahNumber
  /** Arabic name, without the word "سورة" */
  nameAr: string
  /** Latin transliteration — for the future French interface and for search */
  nameLatin: string
}

export const SURAHS: readonly Surah[] = [
  { number: 1, nameAr: "الفاتحة", nameLatin: "Al-Fatiha" },
  { number: 2, nameAr: "البقرة", nameLatin: "Al-Baqara" },
  { number: 3, nameAr: "آل عمران", nameLatin: "Al Imran" },
  { number: 4, nameAr: "النساء", nameLatin: "An-Nisa" },
  { number: 5, nameAr: "المائدة", nameLatin: "Al-Maida" },
  { number: 6, nameAr: "الأنعام", nameLatin: "Al-Anam" },
  { number: 7, nameAr: "الأعراف", nameLatin: "Al-Araf" },
  { number: 8, nameAr: "الأنفال", nameLatin: "Al-Anfal" },
  { number: 9, nameAr: "التوبة", nameLatin: "At-Tawba" },
  { number: 10, nameAr: "يونس", nameLatin: "Yunus" },
  { number: 11, nameAr: "هود", nameLatin: "Hud" },
  { number: 12, nameAr: "يوسف", nameLatin: "Yusuf" },
  { number: 13, nameAr: "الرعد", nameLatin: "Ar-Rad" },
  { number: 14, nameAr: "إبراهيم", nameLatin: "Ibrahim" },
  { number: 15, nameAr: "الحجر", nameLatin: "Al-Hijr" },
  { number: 16, nameAr: "النحل", nameLatin: "An-Nahl" },
  { number: 17, nameAr: "الإسراء", nameLatin: "Al-Isra" },
  { number: 18, nameAr: "الكهف", nameLatin: "Al-Kahf" },
  { number: 19, nameAr: "مريم", nameLatin: "Maryam" },
  { number: 20, nameAr: "طه", nameLatin: "Ta-Ha" },
  { number: 21, nameAr: "الأنبياء", nameLatin: "Al-Anbiya" },
  { number: 22, nameAr: "الحج", nameLatin: "Al-Hajj" },
  { number: 23, nameAr: "المؤمنون", nameLatin: "Al-Muminun" },
  { number: 24, nameAr: "النور", nameLatin: "An-Nur" },
  { number: 25, nameAr: "الفرقان", nameLatin: "Al-Furqan" },
  { number: 26, nameAr: "الشعراء", nameLatin: "Ash-Shuara" },
  { number: 27, nameAr: "النمل", nameLatin: "An-Naml" },
  { number: 28, nameAr: "القصص", nameLatin: "Al-Qasas" },
  { number: 29, nameAr: "العنكبوت", nameLatin: "Al-Ankabut" },
  { number: 30, nameAr: "الروم", nameLatin: "Ar-Rum" },
  { number: 31, nameAr: "لقمان", nameLatin: "Luqman" },
  { number: 32, nameAr: "السجدة", nameLatin: "As-Sajda" },
  { number: 33, nameAr: "الأحزاب", nameLatin: "Al-Ahzab" },
  { number: 34, nameAr: "سبأ", nameLatin: "Saba" },
  { number: 35, nameAr: "فاطر", nameLatin: "Fatir" },
  { number: 36, nameAr: "يس", nameLatin: "Ya-Sin" },
  { number: 37, nameAr: "الصافات", nameLatin: "As-Saffat" },
  { number: 38, nameAr: "ص", nameLatin: "Sad" },
  { number: 39, nameAr: "الزمر", nameLatin: "Az-Zumar" },
  { number: 40, nameAr: "غافر", nameLatin: "Ghafir" },
  { number: 41, nameAr: "فصلت", nameLatin: "Fussilat" },
  { number: 42, nameAr: "الشورى", nameLatin: "Ash-Shura" },
  { number: 43, nameAr: "الزخرف", nameLatin: "Az-Zukhruf" },
  { number: 44, nameAr: "الدخان", nameLatin: "Ad-Dukhan" },
  { number: 45, nameAr: "الجاثية", nameLatin: "Al-Jathiya" },
  { number: 46, nameAr: "الأحقاف", nameLatin: "Al-Ahqaf" },
  { number: 47, nameAr: "محمد", nameLatin: "Muhammad" },
  { number: 48, nameAr: "الفتح", nameLatin: "Al-Fath" },
  { number: 49, nameAr: "الحجرات", nameLatin: "Al-Hujurat" },
  { number: 50, nameAr: "ق", nameLatin: "Qaf" },
  { number: 51, nameAr: "الذاريات", nameLatin: "Adh-Dhariyat" },
  { number: 52, nameAr: "الطور", nameLatin: "At-Tur" },
  { number: 53, nameAr: "النجم", nameLatin: "An-Najm" },
  { number: 54, nameAr: "القمر", nameLatin: "Al-Qamar" },
  { number: 55, nameAr: "الرحمن", nameLatin: "Ar-Rahman" },
  { number: 56, nameAr: "الواقعة", nameLatin: "Al-Waqia" },
  { number: 57, nameAr: "الحديد", nameLatin: "Al-Hadid" },
  { number: 58, nameAr: "المجادلة", nameLatin: "Al-Mujadila" },
  { number: 59, nameAr: "الحشر", nameLatin: "Al-Hashr" },
  { number: 60, nameAr: "الممتحنة", nameLatin: "Al-Mumtahana" },
  { number: 61, nameAr: "الصف", nameLatin: "As-Saff" },
  { number: 62, nameAr: "الجمعة", nameLatin: "Al-Jumua" },
  { number: 63, nameAr: "المنافقون", nameLatin: "Al-Munafiqun" },
  { number: 64, nameAr: "التغابن", nameLatin: "At-Taghabun" },
  { number: 65, nameAr: "الطلاق", nameLatin: "At-Talaq" },
  { number: 66, nameAr: "التحريم", nameLatin: "At-Tahrim" },
  { number: 67, nameAr: "الملك", nameLatin: "Al-Mulk" },
  { number: 68, nameAr: "القلم", nameLatin: "Al-Qalam" },
  { number: 69, nameAr: "الحاقة", nameLatin: "Al-Haqqa" },
  { number: 70, nameAr: "المعارج", nameLatin: "Al-Maarij" },
  { number: 71, nameAr: "نوح", nameLatin: "Nuh" },
  { number: 72, nameAr: "الجن", nameLatin: "Al-Jinn" },
  { number: 73, nameAr: "المزمل", nameLatin: "Al-Muzzammil" },
  { number: 74, nameAr: "المدثر", nameLatin: "Al-Muddaththir" },
  { number: 75, nameAr: "القيامة", nameLatin: "Al-Qiyama" },
  { number: 76, nameAr: "الإنسان", nameLatin: "Al-Insan" },
  { number: 77, nameAr: "المرسلات", nameLatin: "Al-Mursalat" },
  { number: 78, nameAr: "النبأ", nameLatin: "An-Naba" },
  { number: 79, nameAr: "النازعات", nameLatin: "An-Naziat" },
  { number: 80, nameAr: "عبس", nameLatin: "Abasa" },
  { number: 81, nameAr: "التكوير", nameLatin: "At-Takwir" },
  { number: 82, nameAr: "الانفطار", nameLatin: "Al-Infitar" },
  { number: 83, nameAr: "المطففين", nameLatin: "Al-Mutaffifin" },
  { number: 84, nameAr: "الانشقاق", nameLatin: "Al-Inshiqaq" },
  { number: 85, nameAr: "البروج", nameLatin: "Al-Buruj" },
  { number: 86, nameAr: "الطارق", nameLatin: "At-Tariq" },
  { number: 87, nameAr: "الأعلى", nameLatin: "Al-Ala" },
  { number: 88, nameAr: "الغاشية", nameLatin: "Al-Ghashiya" },
  { number: 89, nameAr: "الفجر", nameLatin: "Al-Fajr" },
  { number: 90, nameAr: "البلد", nameLatin: "Al-Balad" },
  { number: 91, nameAr: "الشمس", nameLatin: "Ash-Shams" },
  { number: 92, nameAr: "الليل", nameLatin: "Al-Layl" },
  { number: 93, nameAr: "الضحى", nameLatin: "Ad-Duha" },
  { number: 94, nameAr: "الشرح", nameLatin: "Ash-Sharh" },
  { number: 95, nameAr: "التين", nameLatin: "At-Tin" },
  { number: 96, nameAr: "العلق", nameLatin: "Al-Alaq" },
  { number: 97, nameAr: "القدر", nameLatin: "Al-Qadr" },
  { number: 98, nameAr: "البينة", nameLatin: "Al-Bayyina" },
  { number: 99, nameAr: "الزلزلة", nameLatin: "Az-Zalzala" },
  { number: 100, nameAr: "العاديات", nameLatin: "Al-Adiyat" },
  { number: 101, nameAr: "القارعة", nameLatin: "Al-Qaria" },
  { number: 102, nameAr: "التكاثر", nameLatin: "At-Takathur" },
  { number: 103, nameAr: "العصر", nameLatin: "Al-Asr" },
  { number: 104, nameAr: "الهمزة", nameLatin: "Al-Humaza" },
  { number: 105, nameAr: "الفيل", nameLatin: "Al-Fil" },
  { number: 106, nameAr: "قريش", nameLatin: "Quraysh" },
  { number: 107, nameAr: "الماعون", nameLatin: "Al-Maun" },
  { number: 108, nameAr: "الكوثر", nameLatin: "Al-Kawthar" },
  { number: 109, nameAr: "الكافرون", nameLatin: "Al-Kafirun" },
  { number: 110, nameAr: "النصر", nameLatin: "An-Nasr" },
  { number: 111, nameAr: "المسد", nameLatin: "Al-Masad" },
  { number: 112, nameAr: "الإخلاص", nameLatin: "Al-Ikhlas" },
  { number: 113, nameAr: "الفلق", nameLatin: "Al-Falaq" },
  { number: 114, nameAr: "الناس", nameLatin: "An-Nas" },
]

export function surahByNumber(number: SurahNumber): Surah | undefined {
  return SURAHS[number - 1]
}

/** "سورة الملك" */
export function surahLabel(number: SurahNumber) {
  const surah = surahByNumber(number)
  return surah ? `سورة ${surah.nameAr}` : "—"
}
